server:
  disable: true

clients:
  - url: "${LOKI_URL}"

positions:
  filename: /data/positions.yaml

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      json: false
      labels:
        job: systemd-journal
    # see https://www.freedesktop.org/software/systemd/man/systemd.journal-fields.html#Trusted%20Journal%20Fields
    # see https://grafana.com/docs/loki/latest/clients/promtail/scraping/#journal-scraping-linux-only
    # NB use `journalctl -n 1 -o json | jq .` to see an actual journal log message (including metadata).
    # NB use `journalctl -n 1 -o json CONTAINER_NAME=date-ticker | jq .` to see a container log message.
    relabel_configs:
      - source_labels: [__journal__hostname]
        target_label: host
      - source_labels: [__journal__systemd_unit]
        target_label: source
      - source_labels: [__journal_container_name]
        target_label: container_name
      - source_labels: [__journal_image_name]
        target_label: image_name
      - source_labels: [__journal_workflow_id]
        target_label: workflow_id
      - source_labels: [__journal__boot_id]
        target_label: boot
      - source_labels: [__journal_priority]
        target_label: priority
    pipeline_stages:
      - template:
          source: priority
          template: '{{ if eq .Value "0" }}{{ Replace .Value "0" "emerg" 1 }}{{ else if eq .Value "1" }}{{ Replace .Value "1" "alert" 1 }}{{ else if eq .Value "2" }}{{ Replace .Value "2" "crit" 1 }}{{ else if eq .Value "3" }}{{ Replace .Value "3" "err" 1 }}{{ else if eq .Value "4" }}{{ Replace .Value "4" "warning" 1 }}{{ else if eq .Value "5" }}{{ Replace .Value "5" "notice" 1 }}{{ else if eq .Value "6" }}{{ Replace .Value "6" "info" 1 }}{{ else if eq .Value "7" }}{{ Replace .Value "7" "debug" 1 }}{{ end }}'
      - labels:
          priority: