server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: "${LOKI_URL}"

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs
        host: "${HOSTNAME}"
        __path__: /var/log/*log
