name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
      - name: Test
        run: |
          pip install -r requirements.txt
          pip install dist/*.whl
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: True
          files: |
            dist/*.whl
            dist/*.tar.gz